# services.py
from datetime import datetime
import uuid

from agent import run_agent
from db_postgres import (
    check_active_application,
    log_status_change,
    get_status_history,
)
from llm_service import generate_status_explanation


def generate_application_data(req, use_llm: bool = False):
    """
    FULL PIPELINE:
    1. Create application ID + timestamps
    2. Check active PAN
    3. submitted → processing
    4. Agent run
    5. Manual-review routing
    6. Final decision (approved/rejected)
    7. LLM status explanation (final only)
    """

    data = req.dict()
    data["application_id"] = f"ln_{uuid.uuid4().hex[:12]}"
    data["created_at"] = datetime.utcnow()

    # Pre-fill officer fields (until manual review occurs)
    data["officer_notes"] = None
    data["reviewed_by"] = None

    # ============================================================
    # 1️⃣ PAN CHECK → SUBMITTED
    # ============================================================
    if check_active_application(data["pan"]):
        raise Exception(f"Active application already exists for PAN {data['pan']}")

    old_status = None
    new_status = "submitted"
    data["status"] = new_status

    log_status_change(data["application_id"], old_status, new_status)

    # ============================================================
    # 2️⃣ RUN AGENT
    # ============================================================
    agent_result = run_agent(data, use_llm=use_llm)

    # If validation failed, agent auto-rejects
    if not agent_result["validation"]["success"]:
        data["status"] = "rejected"
        data["credit_score"] = None
        data["risk_level"] = None
        data["decision_reason"] = agent_result["decision"]["reason"]
        return data

    # ============================================================
    # 3️⃣ PROCESSING
    # ============================================================
    old_status = new_status
    new_status = "processing"
    log_status_change(data["application_id"], old_status, new_status)

    # Fill evaluation results
    data["credit_score"] = agent_result["credit_score"]["credit_score"]
    data["risk_level"] = agent_result["risk"]["risk_level"]
    data["decision_reason"] = agent_result["decision"]["reason"]

    # ============================================================
    # 4️⃣ MANUAL REVIEW AUTO-ROUTING
    # ============================================================
    if agent_result["status"] == "manual_review":
        old_status = "processing"
        new_status = "manual_review"
        data["status"] = new_status

        log_status_change(data["application_id"], old_status, new_status)

        # LLM explanation for decision (optional)
        data["llm_explanation"] = agent_result.get("llm_explanation")

        # Status explanation is NOT generated until final approval/rejection
        data["llm_status_explanation"] = None

        return data

    # ============================================================
    # 5️⃣ AUTO FINAL DECISION (approved / rejected)
    # ============================================================
    final_status = agent_result["status"]
    data["status"] = final_status

    log_status_change(data["application_id"], "processing", final_status)

    # Optional LLM explanation generated by agent
    data["llm_explanation"] = agent_result.get("llm_explanation")

    # ============================================================
    # 6️⃣ FULL LLM STATUS EXPLANATION
    # ============================================================
    history = get_status_history(data["application_id"])
    data["llm_status_explanation"] = generate_status_explanation(data, history)

    return data
